### ISSUE TITLE
Warning with grunt 1.0.1

### ISSUE THREAD

**Issue by TomBecker-BD** [unindented/grunt-legal-eagle#18]
grunt has been updated to version 1.0.1. grunt-legal-eagle runs with it, but there is a warning: 

`npm WARN grunt-legal-eagle@0.2.1 requires a peer of grunt@^0.4.0 but none was installed.`

**Comment by unindented** [comment]
Thanks for the heads up. Published version `0.3.0` which shouldn't show the warning.
